-- SCRIPT DE CRIAÇÃO DAS TABELAS

CREATE DATABASE TourTech;
USE TourTech;

-- TABELA DE NÍVEL DE ACESSO
CREATE TABLE nivelAcesso(
idNivelAcesso INT PRIMARY KEY AUTO_INCREMENT,
nivel VARCHAR(15) NOT NULL,
descricao VARCHAR(50) NOT NULL
);

-- TABELA DAS EMPRESAS
CREATE TABLE empresa(
idEmpresa INT PRIMARY KEY AUTO_INCREMENT,
razaoSocial VARCHAR(100) NOT NULL,
nomeFantasia VARCHAR(100),
cnpj CHAR(14) NOT NULL UNIQUE
);

-- TABELA DE USUÁRIO
CREATE TABLE usuario(
idUsuario INT PRIMARY KEY AUTO_INCREMENT,
nome VARCHAR(200) NOT NULL,
email VARCHAR(45) NOT NULL UNIQUE,
senha VARCHAR(12) NOT NULL,
fkNivelAcesso INT,
fkEmpresa INT,
FOREIGN KEY (fkNivelAcesso)
REFERENCES nivelAcesso(idNivelAcesso),
FOREIGN KEY (fkEmpresa)
REFERENCES empresa(idEmpresa)
);

-- TABELA DOS LOGS NO SISTEMA
CREATE TABLE logSistema(
idLog INT PRIMARY KEY AUTO_INCREMENT,
evento VARCHAR(50) NOT NULL,
data DATE NOT NULL,
hora TIME NOT NULL,
fkUsuario INT,
FOREIGN KEY (fkUsuario)
REFERENCES usuario(idUsuario)
);

-- TABELA DOS PAÍSES DE ORIGEM
CREATE TABLE paisOrigem(
idPais INT PRIMARY KEY AUTO_INCREMENT,
nomePais VARCHAR(45) NOT NULL
);
-- TABELA DOS ESTADOS
CREATE TABLE estado(
idEstado INT PRIMARY KEY AUTO_INCREMENT,
nome VARCHAR(45) NOT NULL UNIQUE,
sigla CHAR(2) NOT NULL UNIQUE,
fkPais INT,
FOREIGN KEY (fkPais)
REFERENCES paisOrigem (idPais)
);

-- TABELA DOS MUNICÍPIOS
CREATE TABLE municipio(
idMunicipio INT PRIMARY KEY AUTO_INCREMENT,
nome VARCHAR(100) NOT NULL,
fkEstado INT,
FOREIGN KEY (fkEstado)
REFERENCES estado(idEstado)
);

-- TABELA DOS ATRATIVOS TURÍSTICOS
CREATE TABLE atrativoTuristico(
idAtrativo INT PRIMARY KEY AUTO_INCREMENT,
nome VARCHAR(100) NOT NULL,
categoria VARCHAR(45) NOT NULL,
fkMunicipio INT,
FOREIGN KEY (fkMunicipio)
REFERENCES municipio(idMunicipio)
);

-- TABELA DAS HOSPEDAGENS
CREATE TABLE hospedagem(
idHospedagem INT PRIMARY KEY AUTO_INCREMENT,
nome VARCHAR(100) NOT NULL,
categoria VARCHAR(45) NOT NULL,
endereco VARCHAR(400) NOT NULL, 
multilingue boolean,
contato VARCHAR(15) NOT NULL,
emailComercial VARCHAR(100) NOT NULL,
fkMunicipio INT,
FOREIGN KEY (fkMunicipio)
REFERENCES municipio(idMunicipio)
);

-- TABELA DOS ESTABELECIMENTOS
CREATE TABLE estabelecimentoAlimenticio(
idEstabelecimento INT PRIMARY KEY AUTO_INCREMENT,
nome VARCHAR(100) NOT NULL,
categoria VARCHAR(45) NOT NULL,
endereco VARCHAR(400) NOT NULL, 
multilingue boolean NOT NULL,
contato VARCHAR(15) NOT NULL,
emailComercial VARCHAR(100) NOT NULL,
fkMunicipio INT,
FOREIGN KEY (fkMunicipio)
REFERENCES municipio(idMunicipio)
);

-- TABELA DE TEMPO
CREATE TABLE tempo(
idTempo INT PRIMARY KEY AUTO_INCREMENT,
mes INT NOT NULL,
nomeMes VARCHAR(15) NOT NULL,
ano INT NOT NULL
);

-- TABELA DE FATO - VISITAÇÃO DE ATRATIVOS
CREATE TABLE fatoVisitaAtrativo(
idFatoVisita INT PRIMARY KEY AUTO_INCREMENT,
quantidade INT NOT NULL,
estrangeiro BOOLEAN NOT NULL,
fkTempo INT,
fkAtrativo INT,
FOREIGN KEY (fkTempo)
REFERENCES tempo(idTempo),
FOREIGN KEY (fkAtrativo)
REFERENCES atrativoTuristico(idAtrativo)
);

-- TABELA DE CHEGADA DE TURISTAS (GERAL)
CREATE TABLE chegadaTurismo(
idChegadaTurista INT PRIMARY KEY AUTO_INCREMENT,
quantidade INT NOT NULL,
fkEstado INT,
fkTempo INT,
fkPais INT,
FOREIGN KEY (fkEstado)
REFERENCES estado(idEstado),
FOREIGN KEY (fkTempo)
REFERENCES tempo(idTempo),
FOREIGN KEY (fkPais)
REFERENCES paisOrigem(idPais)
);

-- TABELA DOS TOKENS DE CADASTRO
CREATE TABLE tokenCadastro(
idToken INT PRIMARY KEY AUTO_INCREMENT,
codigoToken VARCHAR(6) NOT NULL,
dataCriacao DATE NOT NULL,
fkEmpresa INT,
fkNivelAcesso INT,
FOREIGN KEY (fkEmpresa)
REFERENCES empresa(idEmpresa),
FOREIGN KEY (fkNivelAcesso)
REFERENCES nivelAcesso(idNivelAcesso)
);

-- TABELA DOS CHAMADOS DE SUPORTE
CREATE TABLE chamadoSuporte(
idChamado INT PRIMARY KEY AUTO_INCREMENT,
nomeCompleto VARCHAR(100) NOT NULL,
email VARCHAR(100) NOT NULL,
situacao VARCHAR(150) NOT NULL,
descricao VARCHAR(500) NOT NULL,
dataAbertura DATE NOT NULL,
horaAbertura TIME NOT NULL,
fkUsuario INT,
FOREIGN KEY (fkUsuario)
REFERENCES usuario(idUsuario)
);

-- TABELA DE LOGS GERAIS
CREATE TABLE logsGerais(
idLogsGerais INT PRIMARY KEY AUTO_INCREMENT,
dataHora DATETIME NOT NULL,
evento VARCHAR(100) NOT NULL,
status VARCHAR(15) NOT NULL,
objeto VARCHAR(30) NOT NULL
);